"""Run all the task's example business questions and save the answers.

Uses the fast RAG path for the direct questions and the multi-agent deep-research
pipeline for the executive/research questions (which need synthesis across
sub-questions). Writes a Markdown transcript to docs/EXAMPLE_ANSWERS.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from athena.retrieval.knowledge_base import KnowledgeBase
from athena.memory.long_term import LongTermMemory
from athena.agents.rag import answer_question
from athena.agents.orchestrator import DeepResearchOrchestrator

# (category, question, mode)  mode = "rag" | "research"
QUESTIONS = [
    ("Customer Intelligence", "What are the most common customer complaints during the last six months?", "rag"),
    ("Customer Intelligence", "Which complaints remain unresolved?", "rag"),
    ("Customer Intelligence", "Which customers are most affected by recurring issues?", "rag"),
    ("Product Intelligence", "Which feature requests appear most frequently across support tickets, customer feedback, and meeting notes?", "rag"),
    ("Product Intelligence", "Which product areas generate the highest volume of negative feedback?", "rag"),
    ("Product Intelligence", "Which requested features have not yet been prioritized?", "rag"),
    ("Engineering Intelligence", "Which issues reported by customers were eventually fixed?", "rag"),
    ("Engineering Intelligence", "What engineering improvements had the highest impact on customer satisfaction?", "rag"),
    ("Engineering Intelligence", "Which product areas generate the most support burden?", "rag"),
    ("Executive Intelligence", "What are the biggest drivers of customer dissatisfaction?", "research"),
    ("Executive Intelligence", "What are the top product improvements that should be prioritized next quarter?", "research"),
    ("Executive Intelligence", "Generate an executive summary of major risks, opportunities, and recommendations.", "research"),
    ("Research Intelligence", "Analyze all available information and generate a comprehensive report identifying trends, recurring problems, customer pain points, and recommended actions.", "research"),
]

OUT = Path(__file__).resolve().parents[1] / "docs" / "EXAMPLE_ANSWERS.md"


def main() -> int:
    kb = KnowledgeBase()
    if not kb.load():
        print("[error] knowledge base not built. Run: python -m athena.scripts.build_index")
        return 1
    mem = LongTermMemory()
    orch = DeepResearchOrchestrator(kb, memory=mem)

    lines = ["# Athena — Answers to the Task's Example Business Questions\n",
             "_Generated by running each question through the live system. "
             "Direct questions use single-shot RAG; executive/research questions use "
             "the multi-agent deep-research pipeline._\n"]

    current_cat = None
    for cat, q, mode in QUESTIONS:
        if cat != current_cat:
            lines.append(f"\n## {cat}\n")
            current_cat = cat
        print(f"[{mode}] {q[:70]}...")
        lines.append(f"### {q}\n")
        lines.append(f"*Mode: {mode}*\n")
        try:
            if mode == "rag":
                ans = answer_question(kb, q)
                lines.append(ans.answer + "\n")
                if ans.citations:
                    lines.append(f"\n**Sources:** {', '.join('`'+c+'`' for c in ans.citations[:8])}\n")
            else:
                res = orch.run(q, use_memory=True)
                lines.append(res.answer + "\n")
                if res.citations:
                    lines.append(f"\n**Sources:** {', '.join('`'+c+'`' for c in res.citations[:8])}\n")
                lines.append(f"\n*Research plan had {len(res.plan)} sub-questions; "
                             f"{len(res.findings)} validated findings.*\n")
        except Exception as e:  # noqa: BLE001
            lines.append(f"> ERROR: {type(e).__name__}: {str(e)[:200]}\n")
        lines.append("\n---\n")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n[ok] wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
